<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYC1221031" failures="1" tests="4" name="com.crm.Vtiger.CreateContacts.CreateContactTest" time="39.622" errors="0" timestamp="2022-08-12T12:19:00 IST" skipped="3">
  <testcase classname="com.crm.Vtiger.CreateContacts.CreateContactTest" name="TocreateContactTest" time="11.907">
    <skipped/>
  </testcase> <!-- TocreateContactTest -->
  <system-out/>
  <testcase classname="com.crm.Vtiger.CreateContacts.CreateContactTest" name="TocreateContactTest" time="10.010">
    <skipped/>
  </testcase> <!-- TocreateContactTest -->
  <system-out/>
  <testcase classname="com.crm.Vtiger.CreateContacts.CreateContactTest" name="TocreateContactTest" time="7.362">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.Vtiger.CreateContacts.CreateContactTest.TocreateContactTest(CreateContactTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- TocreateContactTest -->
  <system-out/>
  <testcase classname="com.crm.Vtiger.CreateContacts.CreateContactTest" name="TocreateContactTest" time="10.343">
    <skipped/>
  </testcase> <!-- TocreateContactTest -->
  <system-out/>
</testsuite> <!-- com.crm.Vtiger.CreateContacts.CreateContactTest -->
